name: Terraform CI

on:
  push:
    branches:
      - main
      - develop


defaults:
  run:
    working-directory: ./terraform

permissions:
  contents: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'develop' && 'dev' || github.ref_name == 'main' && 'prod' }}
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variable
        id: set-environment
        run: echo "ENVIRONMENT=$(if [ '${{ github.ref_name }}' == 'develop' ]; then echo 'dev'; elif [ '${{ github.ref_name }}' == 'main' ]; then echo 'prod'; fi)" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.region }}

      - name: Terraform Init
        run: terraform init -upgrade -backend-config=env/${{ steps.set-environment.outputs.ENVIRONMENT }}/backend.tfvars

      - name: Terraform Format Check
        run: terraform fmt -write=true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
